# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: mysqlbackend
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: mysqlbackend
#   template:
#     metadata:
#       labels:
#         app: mysqlbackend
#     spec:
#       containers:
#       - name: mysql
#         image: mysql:5.6
#         env:                   #enviroment variables
#           - name: MYSQL_ROOT_PASSWORD 
#             value: dbpassword11
#         ports:
#         - containerPort: 3306

#         volumeMounts:
#           - name: mysql-persitant-storage
#             mountPath:  /var/lib/mysql
#           - name: usermanagement-dbcreation-script
#             mountPath:  /docker-entrypoint-initdb.d #https://hub.docker.com/_/mysql Refer Initializing a fresh instance
           


#       volumes: 
#         - name: mysql-persitant-storage
#           persistentVolumeClaim:
#             claimName : azure-managed-disk-pvc  #PVC name from persistant-volume-claim.yml
#         - name: usermanagement-dbcreation-script
#           configMap:
#            name: usermanagement-dbcreation-script  #configmap name from usermanagmentapp_configmap.yml



################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate 
  template: 
    metadata: 
      labels: 
        app: mysql
    spec: 
      containers:
        - name: mysql
          image: mysql:5.6
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: dbpassword11
          ports:
            - containerPort: 3306
              name: mysql    
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql    
            - name: usermanagement-dbcreation-script
              mountPath: /docker-entrypoint-initdb.d #https://hub.docker.com/_/mysql Refer Initializing a fresh instance                                            
      volumes: 
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: azure-managed-disk-pvc
        - name: usermanagement-dbcreation-script
          configMap:
            name: usermanagement-dbcreation-script