# apiVersion: v1
# kind: Service
# metadata:
#   name: mysqlbackendsvc
# spec:
#   selector:
#     app: mysqlbackend
#   ports:
#   - port: 3306
#   clusterIP: None # This means we are going to use Pod IP    

####################
apiVersion: v1
kind: Service
metadata: 
  name: mysql
spec:
  selector:
    app: mysql 
  ports: 
    - port: 3306  
  clusterIP: None # This means we are going to use Pod IP    