apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-managed-disk-pvc
spec:
  storageClassName: managed-premium-retain-sc #name of storageclass
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteOnce
