apiVersion: v1
kind: Service
metadata:
  name: myapplbservice
spec:
  type : LoadBalancer
  selector: 
    app: myapp # Loadbalance traffic across Pods matching this label selector
  ports:
  - name: http
    port: 80 # Service Port
    targetPort: 80 #Container Port
