apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp  #Key value paids
spec:
  containers:
    - name: myapp
      image: stacksimplify/kubenginx:1.0.0
      ports:
       - containerPort: 80