apiVersion: v1
kind: Service
metadata:
  name: azure-files-nginx-service
  labels: 
    app : azurefile-nginx-app
spec:
  type : LoadBalancer
  selector:
    app: azurefile-nginx-app
  ports:
  - port: 80
    targetPort: 80
